# streamlit_app/core/config_io.py
from __future__ import annotations
import pprint
from pathlib import Path
from typing import Any, Dict

def write_fixed_config_py(fixed_config_path: Path, config_dict: Dict[str, Any]) -> None:
    """
    fixed_config.py를 CONFIG = {...} 형태로 덮어쓴다.
    """
    fixed_config_path.parent.mkdir(parents=True, exist_ok=True)
    py_dict = pprint.pformat(config_dict, width=120, sort_dicts=False)
    body = (
        "# AUTO-GENERATED by Streamlit (experiment save)\n"
        "# Do not edit manually unless you know what you're doing.\n\n"
        "CONFIG = " + py_dict + "\n"
    )
    fixed_config_path.write_text(body, encoding="utf-8")
